# 异常



## 一、简介

+ 在程序中，我们通常使用**异常**表示**一种错误，不正常的情况**
+ 不正常
  + **没有按照原有的计划执行的情况**
+ Java是一门面向对象语言，在Java中我们通过异常类型的对象来描述这些不正常的情况
+ 在代码编写期间发生的编写错误导致代码**无法通过编译**，这种情况被称之为**编译错误**
+ 在**代码运行期间**，代码发生了错误，导致程序无法按照原有的计划执行，我们错误我们称之为**异常**
+ Java中提供了**非常多的异常类**来描述代码执行过程中可能会出现的**不正常的情况**
+ 异常是常用类但是它不是具体的某一个类，而是对一系列类的统称

## 二、异常的体系

+ Throwable
  + Exception
    + RuntimeException
  + Error
+ Throwable是所有异常类的父类
+ Exception一般用于描述不严重的问题，可以通过代码做出保护，给出**解决方案**
+ Error一般用于描述非常严重的问题，一旦发生，将导致程序无法正常执行
+ RuntimeException
  + Exception我们称之为**检查性异常**，一旦代码中申明，那么调用者需要给出**解决方案**
  + RuntimeException我们称之为**运行时异常**，哪怕代码中申明，也可以不给出**解决方案**

## 三、自定义异常对象

+ JDK提供的异常对象都是用来描述代码本身可能会出现的问题
+ 我们在编写项目期间，需要使用异常来描述当前项目运行过程可能会发生的问题
  + 此时我们需要使用**自定义异常**来进行描述

```java
package net.wanhe.j2se.day12;

/*
 * 自定义异常类
 * 继承Exception
 * 根据父类生成当前类的构造方法
 */
public class NotMoneyException extends Exception {

	public NotMoneyException() {
		super();
		// TODO Auto-generated constructor stub
	}

	public NotMoneyException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
		// TODO Auto-generated constructor stub
	}

	public NotMoneyException(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

	public NotMoneyException(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}

	public NotMoneyException(Throwable cause) {
		super(cause);
		// TODO Auto-generated constructor stub
	}
}
```

## 四、异常的使用

```java
package net.wanhe.j2se.day12;

public class Student {
	
	private String name;
	
	public Student() {
		
	}

	public Student(String name) {
		super();
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	/*
	 * 买烟
	 * throws
	 * 		名词  在定义方法时 申明该方法在执行的过程中 可能会遇到哪些不正常的情况
	 * 		多个不正常的情况以,隔开
	 * 
	 * throw
	 * 		动词  在方法执行过程中 真正的发生了不正常的情况 使用throw关键字明确的抛出这个异常
	 * 
	 * 一个方法中如果明确的抛出了检查性异常 那么方法上必须申明
	 * 
	 * 如果抛出的是运行时异常，可以不声明
	 * 
	 * 我们在定义方法时申明该方法在执行过程中可能会出现异常
	 * 就是希望 调用者 给出 解决方案
	 */
	public String buySmoke(double money) throws NotMoneyException  {
		System.out.println("出门到小卖部");
		if(money < 60) {
			//创建一个异常对象用来描述当前发生的不正常的情况
			NotMoneyException e = new NotMoneyException();
			throw e;
		}
		System.out.println("买到了中华烟");
		return "中华";
	}
}
```

## 五、异常处理机制

+ 如果调用的方法神明了可能会出现异常
+ 那么我们需要使用**异常处理机制**给出**解决方案**

```java
package net.wanhe.j2se.day12;

public class Test08 {
	
	/*
	 * try 尝试着执行可能会出现异常的方法
	 * 没有异常则正常执行
	 * 如果有异常
	 * catch 捕捉方法执行过程中抛出的异常对象
	 * 执行解决方案
	 * 
	 * catch可以有多个，用于捕捉不同的异常情况给出对应的解决方案
	 * catch捕捉异常的顺序必须从小到大
	 * 
	 * RuntimeException在方法上不需要申明 所有不需要给出解决方案
	 * 
	 * throw关键字和return一样具有结束方法的效果
	 * return 返回一个具体的值 或者结束方法
	 * throw 抛出了一个异常对象的地址
	 * catch将抛出的异常对象的地址赋值给()中的形参
	 */
	public static void main(String[] args) {
		Student s = new Student("张三");
		try {
			String smokeName = s.buySmoke(80);
			System.out.println(smokeName);
		}catch(Exception e) {
			System.out.println("123");
		}catch(NotMoneyException e) {
			System.out.println("自己垫");
		}catch(NotSmokeException e) {
			System.out.println("中华牙膏");
		}
	}

}

```

## 六、异常对象的常用方法

```java
package net.wanhe.j2se.day12;

public class Test09 {
	
	public static void main(String[] args) {
		//创建对象时 给出当前异常对象的提示信息
		NotMoneyException e = new NotMoneyException("没有钱");
		
		//获取当前异常对象的错误提示信息
		String message = e.getMessage();
		System.out.println(message);
		
		//在控制台输出打印当前异常对象的堆栈跟踪信息
		e.printStackTrace();
	}
}
```

## 七、finally

+ 和异常处理机制一起使用
+ 不管有没有异常`finally`中的内容必定会执行

```java
package net.wanhe.j2se.day12;

public class Test08 {
	
	/*
	 * try 尝试着执行可能会出现异常的方法
	 * 没有异常则正常执行
	 * 如果有异常
	 * catch 捕捉方法执行过程中抛出的异常对象
	 * 执行解决方案
	 * 
	 * catch可以有多个，用于捕捉不同的异常情况给出对应的解决方案
	 * catch捕捉异常的顺序必须从小到大
	 * 
	 * RuntimeException在方法上不需要申明 所有不需要给出解决方案
	 * 
	 * throw关键字和return一样具有结束方法的效果
	 * return 返回一个具体的值 或者结束方法
	 * throw 抛出了一个异常对象的地址
	 * catch将抛出的异常对象的地址赋值给()中的形参
	 */
	public static void main(String[] args) {
		Student s = new Student("张三");
		try {
			String smokeName = s.buySmoke(40);
			System.out.println(smokeName);
		}catch(NotMoneyException e) {
			System.out.println("自己垫");
		}catch(NotSmokeException e) {
			System.out.println("中华牙膏");
		}catch(Exception e) {
			System.out.println("123");
		}finally {
			System.out.println("执行了finally");
		}
	}

}

```

## 八、教育管理系统-异常版本

```java
package net.wanhe.edusystem.service.impl;

import net.wanhe.edusystem.dao.UserDao;
import net.wanhe.edusystem.dao.impl.UserDaoImpl;
import net.wanhe.edusystem.exception.UserException;
import net.wanhe.edusystem.pojo.User;
import net.wanhe.edusystem.service.UserService;

public class UserServiceImpl implements UserService {
	
	private UserDao userDao = new UserDaoImpl();

	/*
	 * 注册功能（业务逻辑）
	 */
	public void regist(User user, String repassword) throws UserException {
		//判断两次密码是否一致
		//A.equals(B)
		if(!repassword.equals(user.getPassword())) {
			throw new UserException("两次密码不一致");
		}
		//判断当前账号是否已注册
		User u = userDao.findUserByLoginName(user.getLoginName());
		if(u != null) {
			throw new UserException("该账号已注册，请直接登录");
		}
		userDao.insert(user);
	}

	/*
	 * 登录功能
	 */
	public void login(User user) throws UserException {
		//判断账号名是否已注册
		User u = userDao.findUserByLoginName(user.getLoginName());
		if(u == null) {
			throw new UserException("该账号不存在，请注册");
		}
		//判断密码是否正确
		if(!user.getPassword().equals(u.getPassword())) {
			throw new UserException("密码不正确");
		}
	}

}

```

